# Generated by Django 5.0 on 2024-01-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_student_coursesdata_alter_coursesdata_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coursesdata',
        ),
        migrations.DeleteModel(
            name='student_coursesdata',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
