# Generated by Django 5.0 on 2024-01-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_coursesdata_delete_student_coursesdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_master',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
    ]
